### PR TITLE
Update backend service for Integreatly

### PR DESCRIPTION
**Pull request by weimeilin79**
1. Fix 8081 not expose due to lib change
2. Add threescale automation

### CODE REVIEW

**Comment by aidenkeating** [comment]
@weimeilin79 I'm rebasing the integreatly branch at the moment, are these changes all included in `master`?

**Comment by weimeilin79** [comment]
Yup, with one exception. I had to change the SSO URL for integr8ly. https://github.com/integr8ly/dayinthelife-integration/commit/191803b2733a6894bca5097a2e86f4665f877ba1

**Comment by aidenkeating** [comment]
@weimeilin79 Looks like that change is already on the branch. https://github.com/integr8ly/dayinthelife-integration/blob/integreatly/support/install/ansible/playbooks/openshift/roles/provision_backend/tasks/main.yml#L58.

I noticed the `API_BACKEND_URL` in the same file is hardcoded.

**Comment by weimeilin79** [comment]
Yeah, that is the URL to apicast. Relating to this issue #131 it needs to set to the APICAST staging and production url, but I don’t know what it is yet.

**Comment by aidenkeating** [comment]
@weimeilin79 Makes sense, thanks. Since the changes in 191803b are included in the `integreatly` branch and the branch has been rebased on `master`, are we happy to close this PR?

**Pull request closed without merging**
